[theme]
primaryColor="#d6a0a0"
backgroundColor="#eecef7"
secondaryBackgroundColor="#d6a0a0"
textColor="#000000"
font="serif"

[deprecation]
showPyplotGlobalUse = false

[server]
fileWatcherType = "poll"
